properties:
  configuration:
    ingress:
      external: true
      stickySessions:
        affinity: sticky
      targetPort: 8089
      transport: http
  template:
    scale:
      minReplicas: 1
      maxReplicas: 1
    containers:
      - name: ca-rest-soap-labs
        image: restsoaplabs.azurecr.io/rest-soap-labs:swagger-product-examples-20260611
        env:
          - name: SOAP_DAST_HOST
            value: 0.0.0.0
          - name: SOAP_DAST_VULN_PORT
            value: "8089"
          - name: SOAP_DAST_VULN_PUBLIC_PORT
            value: "443"
          - name: SOAP_DAST_DB_PATH
            value: /tmp/rest_soap_labs.db
        resources:
          cpu: 2.0
          memory: 4Gi
