properties:
  configuration:
    ingress:
      external: true
      targetPort: 8089
      transport: http
  template:
    containers:
      - name: ca-rest-soap-labs
        image: restsoaplabs.azurecr.io/rest-soap-labs:latest
        env:
          - name: SOAP_DAST_HOST
            value: 0.0.0.0
          - name: SOAP_DAST_VULN_PORT
            value: "8089"
          - name: SOAP_DAST_VULN_PUBLIC_PORT
            value: "443"
        resources:
          cpu: 0.5
          memory: 1Gi
