properties:
  configuration:
    ingress:
      external: true
      targetPort: 8088
      transport: http
  template:
    containers:
      - name: soap-dast-lab-safe
        image: REPLACE_WITH_ACR.azurecr.io/soap-dast-lab:latest
        env:
          - name: APP_MODE
            value: safe
          - name: SOAP_DAST_HOST
            value: 0.0.0.0
          - name: SOAP_DAST_PORT
            value: "8088"
          - name: SOAP_DAST_PUBLIC_PORT
            value: "443"
        resources:
          cpu: 0.5
          memory: 1Gi
